os:
  - linux
  - osx
sudo: required

language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules
    - "$HOME/.cache"

install:
  - npm install

script:
  - npm run test
  - npm run translate
